# ชื่อของ Workflow ที่จะแสดงในหน้า Actions
name: Daily Data Sync

on:
  schedule:
    # ตั้งเวลาให้รันทุก 1 ชั่วโมง (ณ นาทีที่ 5 ของทุกชั่วโมง)
    - cron: '5 * * * *'
    # ตั้งเวลาให้รันเพื่อเก็บตกของเมื่อวาน ทุกวันตอน 00:15 น. (เวลาไทย)
    - cron: '15 17 * * *'

  # อนุญาตให้กดรันเองได้จากหน้า Actions (สำหรับทดสอบ)
  workflow_dispatch:

jobs:
  sync-sheet-data:
    # ใช้ OS มาตรฐานของ GitHub
    runs-on: ubuntu-latest

    steps:
    # 1. ดึงโค้ดจาก Repository ของเราลงมา
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. ตั้งค่า Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. ติดตั้ง library ที่จำเป็นจากไฟล์ requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. สร้างไฟล์ credentials.json จาก Secret ที่เราเก็บไว้
    - name: Create gspread credentials file
      run: echo '${{ secrets.GSHEET_CREDENTIALS }}' > credentials.json

    # 5. รันสคริปต์ Python หลักของเรา
    - name: Run the daily sync script
      run: python daily_sync.py
